### ISSUE TITLE
Error when executing Hover Doc

### ISSUE THREAD

**Issue by schizophrenical** [glepnir/lspsaga.nvim#666]
### Describe the bug

I am encountering an error when trying to do ` Lspsaga hover_doc`, error shown below.

This is from a Java source file. Executing `hover_doc` on the `methods` inside the file leads to an error. Trying `vim.lsp.buf.hover` however works with no issues. 

```
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:16: in function 'open_floating_preview'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:102: in function 'handler'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:114: in function 'callback'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:2005: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1391: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

- Open a `Java` file.
- Wait for the LSP server to finish loading.
- Go to a `method` with `JavaDoc`
- Execute `Lspsaga hover_doc`

### Example scenario
Interestingly, executing ` Lspsaga hover_doc` on `method` or `class reference` works.
`Java` file:
```

import baz.Baz;

public class Foo {

    /**
    * Get Foo.
    *
    * @param fooParam params.
    * @return String foo.
    */
    public String getFoo(final String fooParam) { // hover_doc fails here. vim.lsp.buf.hover works
        // Do foo stuff.
    }

    /**
    * Get Baz
    *
    * @param bazParam params.
    * @return String baz.
    */
    public String getBaz(final String bazParam) { // hover_doc fails here. vim.lsp.buf.hover works
        return baz.getBazStuff() + getFoo(bazParam); // hover_doc works here, shows the docs for getFoo and getBazStuff.
    }

}
```

### Expected behavior

`hover_doc` works the same with `vim.lsp.buf.hover`

### Neovim version (nvim -v)

v0.9.0-dev-fd3d30a

### Operating system/version

Windows Subsystem for Linux (WSL) - Ubuntu 20.04

### Terminal name/version

Windows Terminal

### $TERM environment variable

N/A

**Comment by birtles** [comment]
I'm seeing this now after updating to 0.2.3:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:16: in function 'open_floating_preview'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:100: in function 'handler'
        ....mount_nvimJWS6i8/usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by glepnir** [comment]
which commit  and which file?

**Comment by birtles** [comment]
> which commit and which file?

Commit 9c9644d on a typescript file while trying to show type information.

**Comment by exreplay** [comment]
I'm facing the same issue with typescript and vue files.

```
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:16: in function 'open_floating_preview'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:100: in function 'handler'
        ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by glepnir** [comment]
fixed

**Comment by birtles** [comment]
I just updated but I get the same error with the same stack (the line number have shifted slightly but that's all that has changed).

**Comment by glepnir** [comment]
I had test in ts file it works fine ..

**Comment by birtles** [comment]
Hmm, not for me. I still get the following with commit 9ed82f0:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:16: in function 'open_floating_preview'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:100: in function 'handler'
        ....mount_nvim7rBJOI/usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by exreplay** [comment]
For me it now works fine in ts files but i'm still facing the issue with vue files.

**Comment by glepnir** [comment]
![diagnostic](https://user-images.githubusercontent.com/41671631/212463372-78767486-aa92-4b80-a956-af7be9d22292.gif)

**Comment by exreplay** [comment]
![ezgif-4-67bad58cd4](https://user-images.githubusercontent.com/4998475/212463500-f9c97bf7-2f49-4eb0-badf-9de5c3f11643.gif)

**Comment by glepnir** [comment]
I am downloading vue now wait..

**Comment by exreplay** [comment]
i'm using volar for vue files

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/212465277-b9fdb4b9-c93c-42b2-af9c-e9a6aa270943.png)

**Comment by exreplay** [comment]
Is that a vue 2 setup? Because i'm having the issue with vue 3 and the script setup syntax

**Comment by glepnir** [comment]
I don't know just donwload a project from github .

**Comment by exreplay** [comment]
Could you create project by running one of those commands:

```bash
$ npm create vite@latest
$ yarn create vite
$ pnpm create vite
```

- Select `vue` and `typescript`
- Open the project in nvim
- Open the file `App.vue`
- Trigger hover over the import

**Comment by glepnir** [comment]
I got nothing to show no error.

**Comment by glepnir** [comment]
`import` no hover doc . in helloword

![image](https://user-images.githubusercontent.com/41671631/212465716-1ade0f10-ce3e-4014-9ceb-bc4ae54af880.png)

**Comment by glepnir** [comment]
`import` no hover doc . in helloword

![image](https://user-images.githubusercontent.com/41671631/212465716-1ade0f10-ce3e-4014-9ceb-bc4ae54af880.png)

**Comment by exreplay** [comment]
Ok that is weird because it worked perfectly fine before i upgraded lspsage. I will check my volar config, maybe the error is on my side. Thanks for your effort!

**Comment by glepnir** [comment]
I also tried the `lua vim.lsp.buf.hover()` in import also nothing to show `No information available`

**Comment by exreplay** [comment]
The weird thing is, when i trigger hover with `lua vim.lsp.buf.hover()` everything works find, it shows me the hover overlay.
 
![Bildschirm­foto 2023-01-14 um 10 47 03](https://user-images.githubusercontent.com/4998475/212466070-6bff4b7c-8b34-4e73-9887-233f5125485d.png)

But when i change it back to `Lspsaga hover_doc` i'm getting the error as you can see above.

**Comment by glepnir** [comment]
did you update ? which commit ?

**Comment by exreplay** [comment]
I'm so sorry, my bad. I thought i already `PackerSync` but now i'm on the latest commit and everything is working. Thank you very much for your support!

**Comment by glepnir** [comment]
no problem.

**Comment by glepnir** [comment]
create a new issue
