### ISSUE TITLE
Error when calling `lsp_finder`

### ISSUE THREAD

**Issue by bogdanp05** [glepnir/lspsaga.nvim#835]
### Describe the bug

When calling `lsp_finder`, I get a key error 
```
Error detected while processing CursorMoved Autocommands for "<buffer=10>":
Error executing lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:672: invalid key: title
stack traceback:
        [C]: in function 'nvim_win_set_config'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:672: in function 'open_preview'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:410: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:408>
```

The bug is introduced [here](https://github.com/glepnir/lspsaga.nvim/commit/9b1443017a68213655debd0c0901c22c18bb92a8#diff-77f90d58b006070e19447232c30111b1f494cd6083cf8ccfd173e909d27263f4R672). I get the same error for `title_pos`. It's weird that according to the [neovim docs](https://neovim.io/doc/user/api.html#nvim_open_win()) those keys should be valid.

### Steps to reproduce

`:Lspsaga lsp_finder`

### Expected behavior

`lsp_finder` should work without errors.

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

9a7013874a9d5e0413039fc9ded613fcdbd59cbd

### Terminal name/version

iTerm2  3.4.19

**Comment by bogdanp05** [comment]
thanks for the fix @glepnir !

**Comment by brendencallahan** [comment]
I'm getting a different error, when the preview file is not modifiable. You can lsp_finder over 'set' in vim.keymap.set if you would like to reproduce.

![image](https://user-images.githubusercontent.com/47364240/216804701-24faf8ea-9a3a-4379-96d0-fbf0f0dd1657.png)

**Comment by glepnir** [comment]
fixed.

**Comment by ToppDev** [comment]
I am on `c5b1ad8` and I get a similar error when opening code actions on a module in Rust

```Rust
#[cfg(test)]
mod tests { // <--- Cursor on the word tests
```
Executing the command `:Lspsaga code_action'

Leads to this error, whichs seems related to the lsp_finder error, so I did not open up a new issue
```
Error detected while processing CursorMoved Autocommands for "<buffer=119>":
Error executing lua callback: .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:295: attempt to index field 'textDocument' (a nil value)
stack traceback:
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:295: in function 'get_action_diff'
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:335: in function 'action_preview'
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:180: in function 'set_cursor'
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:73: in function <.../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:72>
```

**Comment by glepnir** [comment]
why you think is same ? code action not finder

**Comment by glepnir** [comment]
fixed.

**Comment by ToppDev** [comment]
because it was also related to `CursorMoved Autocommands` but you are right. Thanks for fixing

**Comment by glepnir** [comment]
I don't get your point. you opened codeaction window.

**Comment by brendencallahan** [comment]
> fixed.

Wow! That was fast. Unfortunately, the issue is still there. It seems you fixed it when it initially opens but if you scroll down to a 'reference', when you scroll back up to 'definition' the error will still appear. (I can provide a screenshot but it is verbatim the same error just under different circumstances.)

Thank you for the quick fixes!

**Comment by brendencallahan** [comment]
fixed.

Wow! That was fast. Unfortunately, the issue is still there. It seems you fixed it when it initially opens but if you scroll down to a 'reference', when you scroll back up to 'definition' the error will still appear.

Thank you for the quick fixes!

**Comment by brendencallahan** [comment]
Wow! Thank you for the quick fixes. Unfortunately, it seems there is still an issue. To reproduce, lspsaga_finder over 'set' in vim.keymap.set and scroll down to 'references' when you scroll back to 'definition' you will get this error. Thanks again for your hard work.

![image](https://user-images.githubusercontent.com/47364240/216821101-31d7b65f-ec2e-4d4b-99b7-34bbfd87dd6c.png)

**Comment by brendencallahan** [comment]
Just updated with your recent fix and it all works as expected. Much appreciated!
